name: Daily Economic Data Report

on:
  workflow_dispatch: # 允許手動觸發
  schedule:
    # CRON 排程: 每天 00:00 (UTC) 執行
    # 這相當於台灣/香港時間 (UTC+8) 的上午 8:00
    - cron: '0 0 * * 2-6'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      # 步驟 1: 取得你的 repository 程式碼
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步驟 2: 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 步驟 3: 安裝系統依賴 (中文字體)
      - name: Install system dependencies (fonts)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
      
      # 步驟 4: 安裝 Python 套件
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 步驟 5: 檢查前一天美股是否開盤 (關鍵步驟)
      - name: Check if US market was open yesterday
        id: market_check # 給這個步驟一個 ID，方便後續引用
        run: python check_market_day.py

      # 步驟 6: 如果檢查通過，才執行主腳本
      # 使用 `if` 條件判斷，只有當 market_check 步驟的輸出 should_run 為 'true' 時才執行
      - name: Run main script if market was open
        if: steps.market_check.outputs.should_run == 'true'
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python test.py

      # 步驟 7: 如果檢查不通過，印出訊息 (可選)
      - name: Log skipped run
        if: steps.market_check.outputs.should_run == 'false'
        run: echo "Skipping report because the market was closed."
